name: Build and Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        python -m pip install --upgrade pip
        pip install twine  # Install Twine

    - name: Adjust Docker command in Makefile
      run: |
        sed -i 's/docker run -it/docker run/g' Makefile # Adjust if needed

    - name: Build
      run: make build

  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Extract tag name
          id: extract_tag
          run: echo "::set-output name=tag_name::$(echo ${GITHUB_REF#refs/tags/})"

        - name: Debug output
          run: |
            echo "GITHUB_REF: $GITHUB_REF"
            echo "Extracted TAG_NAME: ${{ steps.extract_tag.outputs.tag_name }}"

        - name: List contents of dist directory
          run: ls -l ./dist
    
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: 'v0.1.1'
            release_name: "Release v0.1.1"
            draft: false
            prerelease: false

        - name: Find wheel file
          id: find_wheel
          run: |
            echo "WHEEL_PATH=$(ls ./dist/*.whl)" 
            echo "WHEEL_PATH=${WHEEL_PATH}" >> $GITHUB_ENV


        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }} # This is the upload URL for the created release
            asset_path: ${{ env.WHEEL_PATH }}
            asset_name: ${{ env.WHEEL_PATH }}
            asset_content_type: application/octet-stream
